/** tiny copy helper with english/taglish variants and simple runtime switching */
export type Messages = Record<string, string>;
export type Bundle = { english: Messages; taglish: Messages };

const english: Messages = {
  site_title: "QuickGig • Find Gigs Fast in the Philippines",
  nav_find: "Find work",
  nav_saved: "Saved",
  nav_account: "Account",
  nav_account_desc: "Your saved and applied jobs",
  nav_post: "Post a job",
  nav_post_job: "Post a job",
  nav_signin: "Sign in",
  nav_signout: "Sign out",
  nav_language: "Language",
  home_hero_title: "Hanap trabaho made simple",
  home_hero_cta: "Search gigs near you and apply in minutes.",
  search_placeholder: "Search jobs (keyword, company…)",
  search_filters: "Filters",
  search_title: "Find work",
  search_empty: "No results yet. Try different keywords or clearing filters.",
  search_results_count: "{total} results",
  jobs_featured: "Featured jobs",
  saved_title: "Saved jobs",
  saved_empty: "You haven’t saved any jobs yet.",
  saved_badge: "Saved",
  applied_title: "Applied",
  applied_empty: "Nothing yet. Apply now!",
  applied_badge: "Applied",
  job_apply: "Apply now",
  job_applied: "Applied",
  job_save: "Save",
  job_saved: "Saved",
  job_apply_title: "Apply to this job",
  apply_name: "Full name",
  apply_email: "Email",
  apply_resume: "Resume or note",
  apply_submit: "Submit application",
  apply_success: "Application sent",
  apply_error: "Something went wrong. Please try again.",
  login_title: "Sign in",
  login_email: "Email",
  login_password: "Password",
  login_submit: "Sign in",
  login_hint: "Use your email and password. No account? it's okay, not required yet.",
  navbar_signin: "Sign in",
  navbar_account: "Account",
  navbar_employer_inbox: "Employer inbox",
  navbar_logout: "Logout",
  employer_post: "Post a job",
  employer_title: "Employer",
  employer_jobs_title: "My jobs",
  employer_applicants_title: "Applicants",
  employer_empty: "No applicants yet.",
  jobs_title: "Jobs",
  applicants_title: "Applicants",
  status_new: "New",
  status_shortlist: "Shortlist",
  status_interview: "Interview",
  status_hired: "Hired",
  status_rejected: "Rejected",
  shortlist: "Shortlist",
  interview: "Interview",
  hire: "Hire",
  reject: "Reject",
  bulk_selected: "{n} selected",
  export_csv: "Export CSV",
  copy_emails: "Copy Emails",
  notes: "Notes",
  notes_placeholder: "Add notes…",
  copied_to_clipboard: "Copied to clipboard",
  no_applicants_for_filter: "No applicants for this filter",
  applicants_empty: "No applicants yet. Share the job link to get applications.",
  view_applicants: "View applicants",
  my_jobs: "My jobs",
  footer_about: "About",
  footer_terms: "Terms",
  footer_privacy: "Privacy",
  footer_copyright: "© {year} QuickGig.ph",
  err404_title: "Page not found",
  err404_body: "We couldn’t find that page. Try the homepage.",
  err500_title: "Something went wrong",
  err500_body: "Please retry or go back to the homepage.",
  not_found: "Page not found",
  'profile.title': 'My Profile',
  'profile.subtitle': 'Manage your details',
  'field.name': 'Name',
  'field.email': 'Email',
  'field.phone': 'Phone',
  'field.city': 'City',
  'field.barangay': 'Barangay',
  'field.roles': 'Roles',
  'field.expectedRate': 'Expected rate',
  'field.resumeUrl': 'Resume URL',
  'field.bio': 'Bio',
  'action.save': 'Save',
  'saved_success': 'Saved',
  'alerts.title': 'Job Alerts',
  'alerts.empty_title': 'No alerts yet',
  'alerts.empty_body': 'Save a search to get updates.',
  'alerts.create_success': 'Alert saved',
  'alerts.delete_success': 'Alert deleted',
  'alerts.mute': 'Mute',
  'alerts.unmute': 'Unmute',
  'alerts.freq_daily': 'daily',
  'alerts.freq_weekly': 'weekly',
  'alerts.view_results': 'View results',
  'alerts.bell_tooltip_on': 'Edit alert',
  'alerts.bell_tooltip_off': 'Save this search to get daily updates.',
  'messages.title': 'Messages',
  'messages.empty': 'No messages yet',
  'messages.send': 'Send',
  'messages.placeholder': 'Type a message…',
  'messages.unread': 'Unread',
  'messages.new_from': 'New message from {name}',
  'messages.open': 'Open',
  'messages.to_employer': 'Message employer',
  'messages.to_applicant': 'Message applicant',
  'onboarding.title': 'Complete your profile',
  'onboarding.subtitle': 'Finish these steps to start applying.',
  'onboarding.progress': '{score}% complete',
  'onboarding.cta_profile_basic': 'Add basic info',
  'onboarding.cta_profile_contact': 'Add contact info',
  'onboarding.cta_roles': 'Add roles or skills',
  'onboarding.cta_resume': 'Add resume link',
  'onboarding.cta_first_save': 'Save a job',
  'onboarding.cta_first_apply': 'Apply to a job',
  'onboarding.done_title': 'Profile complete!',
  'onboarding.done_body': 'Great job. You’re ready to apply.',
  'onboarding.banner_title': 'Complete your profile to get hired faster.',
  'onboarding.banner_cta': 'Complete profile',
  'profile.resume.title': 'Resume',
  'profile.resume.hint': 'Upload resume (PDF or DOC) up to {mb}MB.',
  'profile.resume.replace': 'Replace',
  'profile.resume.remove': 'Remove',
  'profile.resume.too_big': 'File too big. Max {mb}MB.',
  'profile.resume.bad_type': 'Unsupported file type.',
  'profile.resume.saved': 'Resume saved',
  'profile.avatar.title': 'Avatar',
  'profile.avatar.saved': 'Avatar saved',
  'upload.upload': 'Upload',
  'upload.uploading': 'Uploading…',
  'upload.failed': 'Upload failed',
  'upload.rate_limited': 'Too many uploads. Please wait.',
  'upload.too_big': 'File too large',
  'upload.bad_type': 'Unsupported file type',
  'apply.resume_attached': 'Attached: {name}',
  'apply.resume_optional_hint': 'Resume is optional—you can attach now or later.',
  'toast.close': 'Close',
  'error.generic': 'Something went wrong',
  'error.try_again': 'Try again',
  'error.go_home': 'Go home',
  'skip_to_content': 'Skip to content',
  'rate_limited': 'Too many requests. Please try again later.',
  'consent.ask': 'Allow basic analytics cookies?',
  'consent.yes': 'Yes',
  'consent.no': 'Not now',
  'privacy.title': 'Privacy Policy',
  'terms.title': 'Terms and Conditions',
};

const taglish: Messages = {
  site_title: "QuickGig • Hanap Trabaho, Bilis!",
  nav_find: "Hanap trabaho",
  nav_saved: "Na-save",
  nav_account: "Account",
  nav_account_desc: "Mga na-save at inaplayan mo",
  nav_post: "Mag-post ng trabaho",
  nav_post_job: "Mag-post ng trabaho",
  nav_signin: "Mag-log in",
  nav_signout: "Mag-log out",
  nav_language: "Wika",
  home_hero_title: "Hanap trabaho, walang abala",
  home_hero_cta: "Mag-search ng gigs malapit sa’yo at mag-apply agad.",
  search_placeholder: "Maghanap ng trabaho (keyword, company…)",
  search_filters: "Mga filter",
  search_title: "Hanap trabaho",
  search_empty: "Wala pang resulta. Subukan ibang keywords o linisin ang filters.",
  search_results_count: "{total} resulta",
  jobs_featured: "Mga tampok na trabaho",
  saved_title: "Mga na-save na trabaho",
  saved_empty: "Wala ka pang na-save na trabaho.",
  saved_badge: "Na-save",
  applied_title: "Inaplayan",
  applied_empty: "Wala pa. Mag-apply na!",
  applied_badge: "Nakapag-apply",
  job_apply: "Mag-apply ngayon",
  job_applied: "Nakapag-apply na",
  job_save: "I-save",
  job_saved: "Na-save",
  job_apply_title: "Mag-apply sa trabahong ito",
  apply_name: "Buong pangalan",
  apply_email: "Email",
  apply_resume: "Resume o mensahe",
  apply_submit: "Isumite ang application",
  apply_success: "Na-send ang application mo",
  apply_error: "May nangyaring mali. Pakisubukang muli.",
  login_title: "Mag-log in",
  login_email: "Email",
  login_password: "Password",
  login_submit: "Mag-log in",
  login_hint: "Gamitin ang email at password mo. Walang account? okay lang, di muna required.",
  navbar_signin: "Mag-log in",
  navbar_account: "Account",
  navbar_employer_inbox: "Employer inbox",
  navbar_logout: "Mag-log out",
  employer_post: "Mag-post ng trabaho",
  employer_title: "Employer",
  employer_jobs_title: "Mga trabaho ko",
  employer_applicants_title: "Mga aplikante",
  employer_empty: "Wala pang nag-apply",
  jobs_title: "Mga trabaho",
  applicants_title: "Mga aplikante",
  status_new: "Bago",
  status_shortlist: "Shortlist",
  status_interview: "Interview",
  status_hired: "Hired",
  status_rejected: "Rejected",
  shortlist: "Shortlist",
  interview: "Interview",
  hire: "Hire",
  reject: "Reject",
  bulk_selected: "{n} napili",
  export_csv: "I-export ang CSV",
  copy_emails: "Kopyahin emails",
  notes: "Notes",
  notes_placeholder: "Magdagdag ng notes…",
  copied_to_clipboard: "Nakopya na sa clipboard",
  no_applicants_for_filter: "Walang applicants sa filter na ito",
  applicants_empty: "Wala pang applicants. Share mo ang job link para makakuha ng mga application.",
  view_applicants: "Tingnan ang mga aplikante",
  my_jobs: "Mga trabaho ko",
  footer_about: "Tungkol",
  footer_terms: "Terms",
  footer_privacy: "Privacy",
  footer_copyright: "© {year} QuickGig.ph",
  err404_title: "Hindi makita ang page",
  err404_body: "Wala kaming mahanap na ganyang page. Balik sa homepage.",
  err500_title: "May aberya",
  err500_body: "Paki-reload o bumalik sa homepage.",
  not_found: "Hindi makita ang page",
  'profile.title': 'Ang Aking Profile',
  'profile.subtitle': 'Ayusin ang detalye mo',
  'field.name': 'Pangalan',
  'field.email': 'Email',
  'field.phone': 'Telepono',
  'field.city': 'Lungsod',
  'field.barangay': 'Barangay',
  'field.roles': 'Mga role',
  'field.expectedRate': 'Inaasahang bayad',
  'field.resumeUrl': 'Resume URL',
  'field.bio': 'Bio',
  'action.save': 'I-save',
  'saved_success': 'Na-save',
  'alerts.title': 'Job Alerts',
  'alerts.empty_title': 'Wala ka pang alert',
  'alerts.empty_body': 'I-save ang search mo para may updates ka.',
  'alerts.create_success': 'Alert na-save',
  'alerts.delete_success': 'Alert tinanggal',
  'alerts.mute': 'Mute',
  'alerts.unmute': 'Unmute',
  'alerts.freq_daily': 'araw-araw',
  'alerts.freq_weekly': 'lingguhan',
  'alerts.view_results': 'Tingnan ang results',
  'alerts.bell_tooltip_on': 'I-edit ang alert',
  'alerts.bell_tooltip_off': "I-save ang search na ’to para may update ka araw-araw.",
  'messages.title': 'Mga Mensahe',
  'messages.empty': 'Wala pang usapan',
  'messages.send': 'Ipadala',
  'messages.placeholder': 'Mag-type ng mensahe…',
  'messages.unread': 'Di pa nababasa',
  'messages.new_from': 'May bagong message galing kay {name}',
  'messages.open': 'Buksan',
  'messages.to_employer': 'Message employer',
  'messages.to_applicant': 'Message applicant',
  'onboarding.title': 'Kumpletuhin ang profile mo',
  'onboarding.subtitle': 'Tapusin ang mga steps para mas mabilis mag-apply.',
  'onboarding.progress': '{score}% kumpleto',
  'onboarding.cta_profile_basic': 'Magdagdag ng basic info',
  'onboarding.cta_profile_contact': 'Ilagay ang contact info',
  'onboarding.cta_roles': 'Magdagdag ng roles o skills',
  'onboarding.cta_resume': 'Ilagay ang resume link',
  'onboarding.cta_first_save': 'Mag-save ng job',
  'onboarding.cta_first_apply': 'Mag-apply sa job',
  'onboarding.done_title': 'Kumpleto na ang profile!',
  'onboarding.done_body': 'Ready ka nang mag-apply sa mga trabaho.',
  'onboarding.banner_title': 'Kumpletuhin ang profile mo para mas mabilis ma-hire.',
  'onboarding.banner_cta': 'Kumpletuhin',
  'profile.resume.title': 'Resume',
  'profile.resume.hint': 'Mag-upload ng resume (PDF o DOC) hanggang {mb}MB.',
  'profile.resume.replace': 'Palitan',
  'profile.resume.remove': 'Tanggalin',
  'profile.resume.too_big': 'Masyadong malaki ang file. Max {mb}MB.',
  'profile.resume.bad_type': 'Di suportadong file type.',
  'profile.resume.saved': 'Na-save ang resume',
  'profile.avatar.title': 'Avatar',
  'profile.avatar.saved': 'Na-save ang avatar',
  'upload.upload': 'Mag-upload',
  'upload.uploading': 'Nag-a-upload…',
  'upload.failed': 'Bagsak ang upload',
  'upload.too_big': 'Masyadong malaki ang file',
  'upload.bad_type': 'Hindi suportadong file type',
  'apply.resume_attached': 'Naka-attach: {name}',
  'apply.resume_optional_hint': 'Optional lang ang resume—puwede mong i-attach ngayon o sa susunod.',
  'upload.rate_limited': 'Sobra na ang uploads. Pahinga muna.',
  'toast.close': 'Isara',
  'error.generic': 'May nangyaring mali',
  'error.try_again': 'Subukang muli',
  'error.go_home': 'Uwi sa home',
  'skip_to_content': 'Laktawan sa content',
  'rate_limited': 'Sobra na ang requests. Subukan muli mamaya.',
  'consent.ask': 'Payagan ang basic analytics cookies?',
  'consent.yes': 'Oo',
  'consent.no': 'Huwag muna',
  'privacy.title': 'Patakaran sa Privacy',
  'terms.title': 'Mga Tuntunin',
};

const bundle: Bundle = { english, taglish };
export const bundles = { english, taglish };

function readVariantFromEnv(): keyof Bundle {
  const v = (process.env.NEXT_PUBLIC_COPY_VARIANT || "english").toLowerCase();
  return (v === "taglish" ? "taglish" : "english") as keyof Bundle;
}

/** Decide variant: ?lang=tl|en > localStorage('copyVariant') > env */
export function getVariantRuntime(): keyof Bundle {
  if (typeof window === "undefined") return readVariantFromEnv();
  const u = new URL(window.location.href);
  const q = u.searchParams.get("lang");
  if (q === "tl") {
    window.localStorage.setItem("copyVariant", "taglish");
    return "taglish";
  }
  if (q === "en") {
    window.localStorage.setItem("copyVariant", "english");
    return "english";
  }
  const saved = window.localStorage.getItem("copyVariant");
  if (saved === "taglish" || saved === "english") return saved as keyof Bundle;
  return readVariantFromEnv();
}

export function setVariantRuntime(v: "english" | "taglish") {
  if (typeof window !== "undefined") {
    window.localStorage.setItem("copyVariant", v);
  }
}

export function t(key: keyof typeof english, vars?: Record<string, string | number>): string {
  const v = getVariantRuntime();
  const str = (bundle[v][key] ?? bundle.english[key] ?? key) as string;
  return str.replace(/\{(\w+)\}/g, (_, k) => (vars?.[k] ?? "") as string);
}
