insert into public.locations (region, city, region_slug, city_slug) values
  ('Metro Manila','Caloocan','ncr','caloocan'),
  ('Metro Manila','Las Piñas','ncr','las_pinas'),
  ('Metro Manila','Makati','ncr','makati'),
  ('Metro Manila','Malabon','ncr','malabon'),
  ('Metro Manila','Mandaluyong','ncr','mandaluyong'),
  ('Metro Manila','Manila','ncr','manila'),
  ('Metro Manila','Marikina','ncr','marikina'),
  ('Metro Manila','Muntinlupa','ncr','muntinlupa'),
  ('Metro Manila','Navotas','ncr','navotas'),
  ('Metro Manila','Parañaque','ncr','paranaque'),
  ('Metro Manila','Pasay','ncr','pasay'),
  ('Metro Manila','Pasig','ncr','pasig'),
  ('Metro Manila','Pateros','ncr','pateros'),
  ('Metro Manila','Quezon City','ncr','quezon_city'),
  ('Metro Manila','San Juan','ncr','san_juan'),
  ('Metro Manila','Taguig','ncr','taguig'),
  ('Metro Manila','Valenzuela','ncr','valenzuela'),
  ('CALABARZON','Antipolo','calabarzon','antipolo'),
  ('CALABARZON','Batangas City','calabarzon','batangas_city'),
  ('CALABARZON','Lipa','calabarzon','lipa'),
  ('CALABARZON','Lucena','calabarzon','lucena'),
  ('CALABARZON','Calamba','calabarzon','calamba'),
  ('CALABARZON','Sta. Rosa','calabarzon','santa_rosa'),
  ('CALABARZON','San Pablo','calabarzon','san_pablo'),
  ('CALABARZON','Tanauan','calabarzon','tanauan'),
  ('Central Luzon','Angeles','central_luzon','angeles'),
  ('Central Luzon','Olongapo','central_luzon','olongapo'),
  ('Central Luzon','San Fernando (Pampanga)','central_luzon','san_fernando_pampanga'),
  ('Central Luzon','Tarlac City','central_luzon','tarlac_city'),
  ('Central Luzon','Balanga','central_luzon','balanga'),
  ('Central Luzon','Cabanatuan','central_luzon','cabanatuan'),
  ('Central Visayas','Cebu City','central_visayas','cebu_city'),
  ('Central Visayas','Lapu-Lapu','central_visayas','lapu_lapu'),
  ('Central Visayas','Mandaue','central_visayas','mandaue'),
  ('Central Visayas','Dumaguete','central_visayas','dumaguete'),
  ('Central Visayas','Tagbilaran','central_visayas','tagbilaran'),
  ('Western Visayas','Iloilo City','western_visayas','iloilo_city'),
  ('Western Visayas','Bacolod','western_visayas','bacolod'),
  ('Western Visayas','Roxas City','western_visayas','roxas_city'),
  ('Western Visayas','Kalibo','western_visayas','kalibo'),
  ('Davao Region','Davao City','davao_region','davao_city'),
  ('Davao Region','Tagum','davao_region','tagum'),
  ('Davao Region','Panabo','davao_region','panabo'),
  ('Davao Region','Digos','davao_region','digos'),
  ('Northern Mindanao','Cagayan de Oro','northern_mindanao','cagayan_de_oro'),
  ('Northern Mindanao','Iligan','northern_mindanao','iligan'),
  ('Northern Mindanao','Valencia','northern_mindanao','valencia'),
  ('Bicol Region','Legazpi','bicol_region','legazpi'),
  ('Bicol Region','Naga','bicol_region','naga'),
  ('Bicol Region','Sorsogon City','bicol_region','sorsogon_city');
