name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Use public registry
      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      # Clean & install ONLY production deps (no Playwright/dev)
      - name: Install prod deps only
        run: |
          rm -rf node_modules
          npm ci --omit=dev --no-audit --no-fund || npm install --omit=dev --no-audit --no-fund

      # Minimal build (no lint/typecheck in CI build)
      - name: Build
        run: npm run build
