name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint && npm run typecheck
      - name: Import (dry run – no local files in CI)
        run: LEGACY_IMPORT_DRY_RUN=true npm run legacy:import -- --from "$HOME/QuickGig Project/frontend/public/legacy"
      - run: npm run legacy:verify
