name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Prod-only install (no dev deps, no Playwright)
      - name: Install prod deps only
        run: npm ci --omit=dev --no-audit --no-fund || npm install --omit=dev --no-audit --no-fund

      - name: Build
        run: npm run build
