name: Codex Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  codex-review:
    if: ${{ secrets.CODEX_API_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Enable pnpm (corepack)
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm --version
      - run: pnpm add -g @openai/codex
      - name: Run Codex review
        env:
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
        run: codex review --config ./codex/config.json --github-annotate
