name: Codex Auto-Fix

on:
  workflow_run:
    workflows:
      - "Release Check (PR smoke)"
      - "Full E2E"
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: read

jobs:
  trigger:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest

    steps:
      - name: Find PR + failing jobs
        id: info
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const run = context.payload.workflow_run;
            const runId = run.id;

            // map failing job names
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner, repo, run_id: runId
            });
            const failing = jobs.data.jobs
              .filter(j => j.conclusion === 'failure')
              .map(j => j.name);

            // find PR by head_branch
            const prs = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${run.head_branch}`
            });
            const pr = prs.data[0];

            core.setOutput('pr', pr ? String(pr.number) : '');
            core.setOutput('failing', failing.join(', '));
            core.setOutput('runUrl', run.html_url);
            core.setOutput('workflow', run.name);

      - name: Exit if no PR found
        if: steps.info.outputs.pr == ''
        run: echo "No open PR for this run." && exit 0

      - name: Check labels (codex + autofix)
        id: labels
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = Number(core.getOutput('pr'));
            const labels = await github.rest.issues.listLabelsOnIssue({ owner, repo, issue_number: prNumber });
            const names = labels.data.map(l => l.name);
            core.setOutput('ok', (names.includes('codex') && names.includes('autofix')) ? 'true' : 'false');

      - name: Post Codex task comment
        if: steps.labels.outputs.ok == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = Number(core.getOutput('pr'));
            const failing = core.getOutput('failing') || '(unknown)';
            const runUrl = core.getOutput('runUrl');
            const wname = core.getOutput('workflow');
            const prUrl = `https://github.com/${owner}/${repo}/pull/${prNumber}`;
            const body = [
              "codex:self-heal",
              `Workflow: ${wname}`,
              `Failing jobs: ${failing}`,
              `Run: ${runUrl}`,
              `PR: ${prUrl}`,
              "Artifacts: ensure Playwright zip(s) uploaded under 'playwright-report/**' or 'playwright-report-*.zip'.",
              "Task: diagnose failure from logs & traces and push a fix to this PR branch."
            ].join("\n");
            await github.rest.issues.createComment({ owner, repo, issue_number: prNumber, body });
