name: Cutover & Canonical Checks

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  cutover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Ensure Vercel domains are attached (idempotent)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx -y vercel --token "$VERCEL_TOKEN" domains add "${{ vars.APP_DOMAIN }}" --project "${{ vars.VERCEL_PROJECT_ID }}" || true
          npx -y vercel --token "$VERCEL_TOKEN" domains add "${{ vars.APEX_DOMAIN }}" --project "${{ vars.VERCEL_PROJECT_ID }}" || true
          npx -y vercel alias ls --token "$VERCEL_TOKEN" || true
      - name: Verify DNS
        run: npm run verify:dns
      - name: Verify HTTP canonical behavior
        run: npm run verify:http
