name: Deploy API minimal to Hostinger

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'api-minimal/**'
      - '.github/workflows/deploy-api-minimal.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ftps
          local-dir: api-minimal/
          # *** IMPORTANT: exact docroot path for api.quickgig.ph ***
          server-dir: /home/u789476867/domains/quickgig.ph/public_html/api/
          dangerous-clean-slate: true

      - name: Verify API endpoints
        run: |
          set -e
          echo "Probing https://api.quickgig.ph ..."
          curl -fsSL https://api.quickgig.ph/ | tee /tmp/root.json
          curl -fsSL https://api.quickgig.ph/health | tee /tmp/health.json
          node -e "
            const fs=require('fs');
            const root=JSON.parse(fs.readFileSync('/tmp/root.json','utf8'));
            const health=JSON.parse(fs.readFileSync('/tmp/health.json','utf8'));
            if (root.message!=='QuickGig API') { console.error('Root not ok:', root); process.exit(1); }
            if (health.status!=='ok') { console.error('Health not ok:', health); process.exit(1); }
            console.log('API verified ✓');
          "
