name: Deploy API to Hostinger

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-smoke:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/smoke-backend.sh

  deploy:
    runs-on: ubuntu-latest
    needs: pre-smoke
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        if: ${{ secrets.HOSTINGER_HOST && secrets.HOSTINGER_USER && secrets.HOSTINGER_SSH_KEY && secrets.HOSTINGER_REMOTE_DIR }}
        uses: easingthemes/ssh-deploy@v4
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: api.quickgig.ph/
          target: ${{ secrets.HOSTINGER_REMOTE_DIR }}
          args: "-avz --delete"
      - name: Deploy via FTP
        if: ${{ !(secrets.HOSTINGER_HOST && secrets.HOSTINGER_USER && secrets.HOSTINGER_SSH_KEY && secrets.HOSTINGER_REMOTE_DIR) && secrets.HOSTINGER_FTP_SERVER && secrets.HOSTINGER_FTP_USER && secrets.HOSTINGER_FTP_PASSWORD }}
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.HOSTINGER_FTP_SERVER }}
          username: ${{ secrets.HOSTINGER_FTP_USER }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: api.quickgig.ph/
          server-dir: public_html/api/
      - name: Missing deploy secrets
        if: ${{ !(secrets.HOSTINGER_HOST && secrets.HOSTINGER_USER && secrets.HOSTINGER_SSH_KEY && secrets.HOSTINGER_REMOTE_DIR) && !(secrets.HOSTINGER_FTP_SERVER && secrets.HOSTINGER_FTP_USER && secrets.HOSTINGER_FTP_PASSWORD) }}
        run: |
          echo "No deploy secrets provided" && exit 1

  post-smoke:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/smoke-backend.sh
