name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          npm run build
          npx next export

      - name: Deploy to Hostinger (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USER }}
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./out/
          server-dir: /public_html/app/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.DS_Store
            **/*.map
