name: Deploy via hooks
on:
  push:
  pull_request:
jobs:
  deploy:
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger Vercel (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl -sS -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
      - name: Trigger Vercel (PR preview via label)
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')
        run: curl -sS -X POST "${{ secrets.VERCEL_PREVIEW_DEPLOY_HOOK }}"
