name: Deploy via Vercel Hooks (main + label:deploy)
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'vercel.json'
  pull_request:
    types: [ labeled, synchronize ]
    paths:
      - 'src/**'
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'vercel.json'
  workflow_dispatch:
    inputs:
      kind:
        description: 'preview or production'
        required: false
        default: 'preview'
      url:
        description: 'override hook url'
        required: false

jobs:
  deploy:
    # Only run on:
    #  - push to main, OR
    #  - PRs that carry the 'deploy' label
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Call the proper hook depending on context
      - name: Trigger Vercel Deploy Hook (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl -sS -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"

      - name: Trigger Vercel Preview Hook (PR with label:deploy)
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')
        run: curl -sS -X POST "${{ secrets.VERCEL_PREVIEW_DEPLOY_HOOK }}"
