name: Deploy via Vercel Hooks (main + label:deploy)
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'vercel.json'
  pull_request:
    types: [ labeled, synchronize ]
    paths:
      - 'src/**'
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
      - 'vercel.json'
  workflow_dispatch:
    inputs:
      kind:
        description: 'preview or production'
        required: false
        default: 'preview'
      url:
        description: 'override hook url'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decide target
        id: decide
        shell: bash
        run: |
          set -Eeuo pipefail
          kind="skip"

          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            kind="main"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Check PR labels for 'deploy' without needing gh cli
            labels=$(jq -r '.pull_request.labels[].name // empty' <<< '${{ toJson(github.event) }}')
            if grep -qi '^deploy$' <<< "$labels"; then
              kind="pr"
            fi
          fi

          echo "kind=$kind" >> "$GITHUB_OUTPUT"

      - name: Trigger Vercel Deploy Hook
        if: steps.decide.outputs.kind != 'skip'
        env:
          VERCEL_DEPLOY_HOOK: ${{ steps.decide.outputs.kind == 'main' && secrets.VERCEL_DEPLOY_HOOK || secrets.VERCEL_PREVIEW_DEPLOY_HOOK }}
        run: |
          curl -sS -X POST "$VERCEL_DEPLOY_HOOK"
