name: E2E Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC

jobs:
  smoke:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dev deps
        run: npm ci --include=dev --no-audit --no-fund || npm install --include=dev --no-audit --no-fund

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        continue-on-error: true

      - name: Run smoke tests
        env:
          BASE: https://app.quickgig.ph
        run: npm run test:e2e:smoke
        continue-on-error: true

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Finalize (always succeed)
        if: always()
        run: echo "Nightly smoke completed (non-blocking)."
