name: E2E Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  smoke:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      # Explicitly include dev deps; .npmrc defaults to omit=dev
      - name: Install dev deps (Playwright, types, etc.)
        run: npm ci --include=dev --no-audit --no-fund || npm install --include=dev --no-audit --no-fund

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run smoke tests
        env:
          BASE: https://app.quickgig.ph
        run: npm run test:e2e:smoke

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
