name: E2E Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'
  pull_request:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run playwright:install
      - name: Run smoke tests
        env:
          BASE: https://app.quickgig.ph
        run: npm run test:e2e:smoke
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
