name: E2E Smoke

on:
  pull_request:
  push:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Install browsers & required OS deps (avoids 403 and “playwright not found”)
      - name: Install Playwright
        uses: microsoft/playwright-github-action@v1

      # Deploy/resolve Vercel Preview and export the URL
      - name: Vercel Preview
        id: vercel
        uses: vercel/actions/preview@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
        # If you already deploy via Vercel elsewhere, keep this step;
        # the action no-ops and still exposes the latest preview URL.

      - name: Resolve Preview URL
        id: preview
        run: |
          url="${{ steps.vercel.outputs.preview-url }}"
          if [ -z "$url" ] && [ "${{ github.event_name }}" = "pull_request" ]; then
            url=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json comments --jq '.comments[].body' | grep -o 'https://[^ ]*\.vercel\.app' | head -n 1)
          fi
          echo "preview-url=$url" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Preview URL
        run: echo "Preview URL = ${{ steps.preview.outputs.preview-url }}"

      # Optional: seed demo data when explicitly enabled
      - name: Seed demo (optional)
        if: ${{ secrets.SEED_URL != '' && secrets.SEED_TOKEN != '' }}
        run: |
          curl -fsSL -H "Authorization: Bearer ${{ secrets.SEED_TOKEN }}" "${{ secrets.SEED_URL }}"

      - name: Run Playwright smoke
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.preview.outputs.preview-url }}
        run: npm run qa:smoke

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload Playwright traces (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
          retention-days: 7
