name: E2E
on: { pull_request: {} }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: Compute base URL
        run: |
          if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
            echo "PLAYWRIGHT_BASE_URL=https://${{ github.event.pull_request.head.repo.owner.login }}-quickgig-frontend-${{ github.event.number }}.${{ github.repository_owner }}-projects.vercel.app" >> $GITHUB_ENV || true
          fi
          echo "PLAYWRIGHT_BASE_URL=${PLAYWRIGHT_BASE_URL:-http://localhost:3000}" >> $GITHUB_ENV
      - name: href safety
        run: npm run lint:href
      - name: E2E
        run: npm run test:e2e
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
