name: E2E Smoke

on:
  pull_request:
  push:
    branches: [main]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PLAYWRIGHT_LANDING_URL: https://quickgig.ph
      PLAYWRIGHT_APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: true
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SEED_ADMIN_EMAIL: ${{ secrets.SEED_ADMIN_EMAIL }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Seed demo data (optional)
        if: ${{ env.SUPABASE_SERVICE_ROLE_KEY != '' }}
        run: |
          if npm run | grep -q "^  seed"; then
            npm run seed
          else
            echo "No seed script; skipping."
          fi

      - name: Run smoke tests
        run: |
          if npm run | grep -q "^  qa:smoke"; then
            npm run qa:smoke -- --retries=2 --global-timeout=900000
          else
            npx playwright test tests/smoke --reporter=line --retries=2 --global-timeout=900000
          fi

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

