name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * *'   # daily 07:15 UTC

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: "true"
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
      TEST_LOGIN_SECRET: ${{ secrets.TEST_LOGIN_SECRET }}
      TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_LANDING_URL: ${{ env.PREVIEW_URL || secrets.NEXT_PUBLIC_LANDING_URL || secrets.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_SITE_URL:     ${{ secrets.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_APP_URL:      ${{ secrets.NEXT_PUBLIC_APP_URL  || 'http://localhost:3000' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps (robust)
        run: npm install --legacy-peer-deps --no-audit
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run smoke
        run: npm run qa:smoke
        env:
          CI: 'true'
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-smoke
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore

  full-e2e:
    runs-on: ubuntu-latest
    env:
      APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: "true"
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_EMAIL_ADMIN: ${{ secrets.QA_TEST_EMAIL_ADMIN || secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
      TEST_LOGIN_SECRET: ${{ secrets.TEST_LOGIN_SECRET }}
      TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_LANDING_URL: ${{ env.PREVIEW_URL || secrets.NEXT_PUBLIC_LANDING_URL || secrets.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_SITE_URL:     ${{ secrets.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_APP_URL:      ${{ secrets.NEXT_PUBLIC_APP_URL  || 'http://localhost:3000' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps (robust)
        run: npm install --legacy-peer-deps --no-audit
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run full e2e
        run: npm run qa:full
        env:
          CI: 'true'
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-full-e2e
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore
