name: E2E

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_full:
        description: "Run full E2E suite"
        type: boolean
        default: false

concurrency: e2e-${{ github.ref }}

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CI: true
      PLAYWRIGHT_LANDING_URL: https://quickgig.ph
      PLAYWRIGHT_APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: true
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SEED_ADMIN_EMAIL: ${{ secrets.SEED_ADMIN_EMAIL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Use public npm registry
        run: echo "registry=https://registry.npmjs.org/" > .npmrc
      - run: npm ci --no-audit --no-fund --legacy-peer-deps
      - run: npx playwright install --with-deps chromium
      - run: node scripts/seed-demo.js
      - run: node scripts/session-stub.js
      - run: npm run qa:smoke
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            test-results/**
            playwright-report/**
            **/*.zip

  full-e2e:
    needs: smoke
    if: |
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'workflow_dispatch' && inputs.run_full == 'true') ||
      (github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'run-full-e2e'))
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CI: true
      PLAYWRIGHT_LANDING_URL: https://quickgig.ph
      PLAYWRIGHT_APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: true
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SEED_ADMIN_EMAIL: ${{ secrets.SEED_ADMIN_EMAIL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Use public npm registry
        run: echo "registry=https://registry.npmjs.org/" > .npmrc
      - run: npm ci --no-audit --no-fund --legacy-peer-deps
      - run: npx playwright install --with-deps chromium
      - run: node scripts/seed-demo.js
      - run: node scripts/session-stub.js
      - run: npm run qa:e2e
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-artifacts
          path: |
            test-results/**
            playwright-report/**
            **/*.zip
