name: E2E (manual or nightly)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install deps (robust)
        run: |
          npm ci || npm install --no-audit --prefer-offline

      - name: Playwright install
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Start server (background)
        run: |
          nohup npm start >/tmp/next.log 2>&1 &
          npx wait-on http://localhost:3000/health

      - name: Run E2E
        run: npx playwright test --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload Next server log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-log
          path: /tmp/next.log
          if-no-files-found: ignore

      - name: Cleanup test data
        if: always()
        run: npx tsx scripts/e2e/cleanup.ts
