name: E2E (manual or nightly)

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Run against an existing URL (leave blank to build & start locally)"
        required: false
        default: ""
  schedule:
    - cron: "30 8 * * *"  # daily 08:30 UTC (adjust)

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      # Enable test endpoints
      CI_ALLOW_TEST_ENDPOINTS: "1"
      # Supabase test project (set in repo Secrets)
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      # Optional: run against an existing deployment
      BASE_URL: ${{ inputs.base_url || secrets.E2E_BASE_URL || 'http://localhost:3000' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build (only if not using external BASE_URL)
        if: ${{ !inputs.base_url }}
        run: npm run build

      - name: Playwright install
        run: npm run playwright:install

      - name: Seed data
        run: npm run e2e:seed

      - name: Start server (background, only if local)
        if: ${{ !inputs.base_url }}
        run: |
          nohup npm run start:prod > .next-serve.log 2>&1 &
          npx wait-on http://localhost:3000
        env:
          PORT: 3000

      - name: Run E2E
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Next server log
        if: always() && !inputs.base_url
        uses: actions/upload-artifact@v4
        with:
          name: next-server-log
          path: .next-serve.log

      - name: Cleanup data
        if: always()
        run: npx tsx scripts/e2e/cleanup.ts
