name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * *'   # daily 07:15 UTC

jobs:
  preview:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.get-url.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - id: get-url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          url=$(node scripts/get-vercel-preview-url.mjs)
          echo "url=$url" >> $GITHUB_OUTPUT

  smoke:
    needs: preview
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ needs.preview.outputs.url }}
      APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: "true"
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
      TEST_LOGIN_SECRET: ${{ secrets.TEST_LOGIN_SECRET }}
      TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_LANDING_URL: ${{ needs.preview.outputs.url || secrets.NEXT_PUBLIC_LANDING_URL || secrets.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_SITE_URL:     ${{ secrets.NEXT_PUBLIC_SITE_URL || needs.preview.outputs.url || 'http://localhost:3000' }}
      NEXT_PUBLIC_APP_URL:      ${{ secrets.NEXT_PUBLIC_APP_URL  || needs.preview.outputs.url || 'http://localhost:3000' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps
        run: npm run ci:install
      - name: Verify lockfile unchanged
        run: npm run ci:check-lock
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run smoke
        run: npx playwright test -c playwright.ci.ts
        env:
          CI: 'true'
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-smoke
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore

  full-e2e:
    needs: preview
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ needs.preview.outputs.url }}
      APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: "true"
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_EMAIL_ADMIN: ${{ secrets.QA_TEST_EMAIL_ADMIN || secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
      TEST_LOGIN_SECRET: ${{ secrets.TEST_LOGIN_SECRET }}
      TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_LANDING_URL: ${{ needs.preview.outputs.url || secrets.NEXT_PUBLIC_LANDING_URL || secrets.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_SITE_URL:     ${{ secrets.NEXT_PUBLIC_SITE_URL || needs.preview.outputs.url || 'http://localhost:3000' }}
      NEXT_PUBLIC_APP_URL:      ${{ secrets.NEXT_PUBLIC_APP_URL  || needs.preview.outputs.url || 'http://localhost:3000' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps
        run: npm run ci:install
      - name: Verify lockfile unchanged
        run: npm run ci:check-lock
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run full e2e
        run: npx playwright test -c playwright.ci.ts
        env:
          CI: 'true'
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-full-e2e
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore
