name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * *'   # daily 07:15 UTC

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      APP_URL: https://app.quickgig.ph
      PLAYWRIGHT_LANDING_URL: https://quickgig.ph
      PLAYWRIGHT_APP_URL: https://app.quickgig.ph
      NEXT_PUBLIC_APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: "true"
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps (robust)
        run: npm install --legacy-peer-deps --no-audit
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run smoke
        run: npm run qa:smoke
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-smoke
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore

  full-e2e:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      APP_URL: https://app.quickgig.ph
      PLAYWRIGHT_LANDING_URL: https://quickgig.ph
      PLAYWRIGHT_APP_URL: https://app.quickgig.ph
      QA_TEST_MODE: "true"
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_EMAIL_ADMIN: ${{ secrets.QA_TEST_EMAIL_ADMIN || secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps (robust)
        run: npm install --legacy-peer-deps --no-audit
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run full e2e
        run: npm run qa:full
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-full-e2e
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore
