name: Full E2E (disabled while product is WIP)
on:
  workflow_dispatch:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "E2E temporarily disabled. Re-enable after product stabilizes."
