name: Final QA

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e_smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Install Playwright (with deps)
        run: npx playwright install --with-deps

      - name: Resolve Vercel Preview URL
        id: preview
        shell: bash
        run: |
          if [ -n "${PREVIEW_URL}" ]; then
            echo "url=${PREVIEW_URL}" >> "$GITHUB_OUTPUT"
          elif [ -n "${VERCEL_PREVIEW_URL}" ]; then
            echo "url=${VERCEL_PREVIEW_URL}" >> "$GITHUB_OUTPUT"
          else
            echo "url=" >> "$GITHUB_OUTPUT"
          fi

      - name: Show BASE_URL
        run: echo "BASE_URL=${{ steps.preview.outputs.url }}"

      - name: Run smoke tests
        id: smoke
        env:
          BASE_URL: ${{ steps.preview.outputs.url }}
        run: npm run test:smoke
        continue-on-error: true

      - name: Always collect smoke artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            test-results/**
            playwright-report/**
            smoke-artifacts.zip
          if-no-files-found: ignore
          retention-days: 7

      - name: Take QA screenshots (still try even if smoke failed)
        if: always()
        env:
          BASE_URL: ${{ steps.preview.outputs.url }}
        run: npm run qa:screens || true

      - name: Upload QA screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-screens
          path: test-results/screens/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Trigger self-heal (only if smoke failed)
        if: steps.smoke.outcome != 'success'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Codex Self-Heal (E2E)
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          inputs: |
            previewUrl=${{ steps.preview.outputs.url }}
            reason=final-qa smoke failed
