name: Final QA (full)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      E2E_MODE: FULL
      NEXT_PUBLIC_SUPABASE_URL: http://example.com
      NEXT_PUBLIC_SUPABASE_ANON_KEY: anon
      NEXT_PUBLIC_APP_ORIGIN: http://localhost:3000
      SUPABASE_SERVICE_ROLE: stub_service_role
      SEED_ADMIN_EMAIL: ci-admin@example.test
      SEED_ADMIN_PASSWORD: Passw0rd!ci
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20.11.1 }

      - name: Install dependencies (deterministic with fallback)
        run: |
          echo "Node $(node -v) / npm $(npm -v)"
          npm ci || (echo "npm ci failed (lockfile drift) → falling back to npm install"; npm install)

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium

      - name: Typecheck + preflight
        run: |
          npm run ci:verify || true
          npm run typecheck

      - name: Write .env.local
        run: |
          cat > .env.local <<'EOF2'
          NEXT_PUBLIC_SUPABASE_URL=http://example.com
          NEXT_PUBLIC_SUPABASE_ANON_KEY=anon
          NEXT_PUBLIC_APP_ORIGIN=http://localhost:3000
          SUPABASE_SERVICE_ROLE=stub_service_role
          SEED_ADMIN_EMAIL=ci-admin@example.test
          SEED_ADMIN_PASSWORD=Passw0rd!ci
          EOF2

      - name: Build
        run: npm run build

      - name: Start app (background, tee logs)
        run: |
          (npm start 2>&1 | tee .next-app.log) & echo $! > .next-app.pid

      - name: Wait for /api/health or homepage
        run: |
          for i in $(seq 1 60); do
            curl -fsS http://localhost:3000/api/health && exit 0 || true
            curl -fsS http://localhost:3000/ && exit 0 || true
            sleep 1
          done
          echo "App not ready"; exit 1

      - name: Run Full tests
        run: npx playwright test --reporter=line

      # ---- Artifacts ----
      - name: Upload Playwright HTML
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: playwright-report, path: playwright-report/** }

      - name: Upload JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: junit-xml, path: test-results/junit.xml }

      - name: Upload traces/videos/screens
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results/**/*.zip
            test-results/**/*.webm
            test-results/**/*-failed-*.png

      - name: Upload Next server log
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: next-app-log, path: .next-app.log }

      - name: Stop app
        if: always()
        run: |
          if [ -f .next-app.pid ]; then kill $(cat .next-app.pid) || true; fi
