name: Full E2E

on:
  workflow_dispatch: {}
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    env:
      NEXT_PUBLIC_APP_ORIGIN: ${{ secrets.NEXT_PUBLIC_APP_ORIGIN || 'https://app.quickgig.ph' }}
      APP_ORIGIN:             ${{ secrets.APP_ORIGIN || 'https://app.quickgig.ph' }}
      NEXT_PUBLIC_SUPABASE_URL:      ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || '' }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || '' }}
      BASE_URL: http://localhost:3000
      PORT: 3000
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build
        run: pnpm build

      - name: Start app (background)
        run: |
          pnpm start &> .next-app.log &
          npx wait-on --timeout 120000 http://localhost:3000
          curl -fsS http://localhost:3000/ | head -n 40

      - name: Run Full E2E
        run: pnpm exec playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Next server log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-server-log
          path: .next-app.log
          if-no-files-found: ignore
          retention-days: 7
