name: Full E2E
on:
  workflow_dispatch:
    inputs:
      BASE_URL:
        description: "Optional external BASE_URL; empty = run locally"
        required: false
        default: ""
  push:
    branches: [ "main" ]

concurrency:
  group: full-e2e-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      NODE_ENV: production
      PORT: 3000
      LOCAL_BASE_URL: http://localhost:3000

      # ------- EXISTING app/env variables -------
      NEXT_PUBLIC_APP_ORIGIN: ${{ secrets.NEXT_PUBLIC_APP_ORIGIN }}
      APP_ORIGIN: ${{ secrets.NEXT_PUBLIC_APP_ORIGIN }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}

      # ------- OPTIONAL E2E secrets (safe fallbacks if absent) -------
      E2E_KEY: ${{ secrets.E2E_KEY }}
      E2E_EMPLOYER_EMAIL: ${{ secrets.E2E_EMPLOYER_EMAIL }}
      E2E_WORKER_EMAIL:   ${{ secrets.E2E_WORKER_EMAIL }}
      E2E_PASSWORD:       ${{ secrets.E2E_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Note: Use npm install here because E2E runs may coincide with lockfile drift.
      # Release workflows can stay strict with `npm ci`.
      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps
          node -e "console.log('Playwright version:', require('@playwright/test/package.json').version)"

      - name: Build
        run: npm run build

      - name: Start app (background)
        run: |
          nohup npm run start -- -p $PORT > .next-app.log 2>&1 &
          echo $! > .app-pid

      - name: Wait for app to be ready
        run: |
          for i in {1..60}; do
            if curl -fsS "http://localhost:${PORT}/" >/dev/null; then echo "Server is up"; break; fi
            sleep 1
          done

      - name: Determine BASE_URL
        id: base
        run: |
          if [ -n "${{ github.event.inputs.BASE_URL }}" ]; then
            echo "BASE_URL=${{ github.event.inputs.BASE_URL }}" >> $GITHUB_OUTPUT
          else
            echo "BASE_URL=${LOCAL_BASE_URL}" >> $GITHUB_OUTPUT
          fi

      - name: Seed test data
        run: npm run db:seed:test

      - name: Run Full E2E regression pack
        env:
          BASE_URL: ${{ steps.base.outputs.BASE_URL }}
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-e2e
          path: playwright-report
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Next server log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-app.log
          path: .next-app.log
          if-no-files-found: warn
          retention-days: 7

      - name: Stop app
        if: always()
        run: |
          if [ -f .app-pid ]; then kill $(cat .app-pid) || true; fi
