name: Go Live

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Revalidate frontend caches
        env:
          APP_ORIGIN: https://app.quickgig.ph
          REVALIDATE_SECRET: ${{ secrets.REVALIDATE_SECRET }}
        run: |
          set -euo pipefail
          curl -fsS -X POST "$APP_ORIGIN/api/revalidate?secret=$REVALIDATE_SECRET&tag=events"
