name: Lock Guard
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lock_guard:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true
      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Refresh lockfile only (no install)
        run: |
          npm install --package-lock-only --ignore-scripts --audit=false --fund=false --loglevel=error
      - name: Commit & push lockfile if changed
        run: |
          if ! git diff --quiet -- package-lock.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore(lockfile): sync package-lock.json (CI self-heal)"
            git push origin "HEAD:${{ github.head_ref }}"
          else
            echo "No lockfile changes detected."
          fi
