name: Supabase Migrations (manual)
on:
  workflow_dispatch: {}
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with: { version: latest }
      - name: Push migrations to remote
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ] || [ -z "$SUPABASE_PROJECT_REF" ]; then
            echo "Missing SUPABASE_ACCESS_TOKEN or SUPABASE_PROJECT_REF"; exit 1
          fi
          supabase link --project-ref "$SUPABASE_PROJECT_REF" --password "$SUPABASE_ACCESS_TOKEN"
          supabase db push
        # NOTE: provide the two secrets in repo settings if you want to use this.
