name: ops-clean-api-docroot
on: { workflow_dispatch: {} }
jobs:
  clean_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean-slate deploy minimal API
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:     ${{ secrets.FTP_SERVER }}
          username:   ${{ secrets.FTP_USERNAME }}
          password:   ${{ secrets.FTP_PASSWORD }}
          port:       ${{ secrets.FTP_PORT || 21 }}
          protocol:   ftps
          local-dir:  api-minimal/
          server-dir: /home/u789476867/domains/quickgig.ph/public_html/api/
          dangerous-clean-slate: true
