name: Release Check (PR smoke)

on:
  pull_request:
    branches: [ main ]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Typecheck + preflight
        run: |
          # keep light guardrails (typecheck/lint if present)
          npm run ci:verify || true
          npm run typecheck || true
      - name: Write .env.local
        run: |
          cat > .env.local <<'EOF'
          NEXT_PUBLIC_SUPABASE_URL=http://localhost:3000/api/mock
          NEXT_PUBLIC_SUPABASE_ANON_KEY=stub
          NEXT_PUBLIC_APP_ORIGIN=http://localhost:3000
          SUPABASE_SERVICE_ROLE=stub_service_role
          SEED_ADMIN_EMAIL=ci-admin@example.test
          SEED_ADMIN_PASSWORD=Passw0rd!ci
          EOF
      - name: Build
        run: npm run build
      - name: Start app (background, tee logs)
        run: |
          npm start 2>&1 | tee .next-app.log & echo $! > .next-app.pid
      - name: Wait for /api/health or homepage
        run: |
          for i in $(seq 1 60); do
            curl -fsS http://localhost:3000/api/health && exit 0 || true
            curl -fsS http://localhost:3000/ >/dev/null && exit 0 || true
            sleep 1
          done
          echo "App failed to become healthy" >&2
          exit 1
      # ⛔️ No tests for now — we’re focusing on features.
      # Artifacts are skipped to keep the job minimal.
      - name: Stop app
        if: always()
        run: |
          if [ -f .next-app.pid ]; then kill $(cat .next-app.pid) || true; fi
