name: Release Check (PR smoke)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm', cache-dependency-path: package-lock.json }
      - name: Install deps (robust)
        run: |
          npm ci --no-audit --no-fund || (sleep 10 && npm ci --no-audit --no-fund)
      - name: Build
        env:
          DISABLE_STRIPE: '1'
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon
        run: npm run build

  e2e_smoke:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm', cache-dependency-path: package-lock.json }
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Install Playwright (system deps)
        run: npx playwright install --with-deps
      - name: Run Playwright (smoke)
        # Keep it simple: one pass, fast
        run: npx playwright test --reporter=github,html --project=smoke
        env:
          DISABLE_STRIPE: '1'
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon
      - name: Upload smoke report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-smoke
          path: playwright-report/**
