name: PR Title Guard (non-blocking)
on:
  pull_request:
    types: [opened, edited, synchronize]
permissions:
  contents: read
  pull-requests: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const required = ['FEAT-', 'fix(', 'chore(', 'feat('];
            const title = context.payload.pull_request.title || '';
            const body  = context.payload.pull_request.body  || '';
            const ok = required.some(k => title.includes(k) || body.includes(k));
            if (!ok) {
              core.notice('Add a Feature ID from docs/product/BASELINE.md (e.g., FEAT-PSGC-STATIC) or a conventional commit prefix. Non-blocking notice.');
            } else {
              core.info('Title/body includes a Feature ID or conventional prefix.');
            }
