name: Release Check (PR smoke)
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions: { contents: read }
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps (non-CI)
        run: npm install --no-audit --no-fund

      - name: Typecheck + lint (best-effort)
        run: |
          npm run -s typecheck || echo "::warning::no typecheck script"
          npm run -s lint || echo "::warning::no lint script"

      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:3000/api/mock
          NEXT_PUBLIC_SUPABASE_ANON_KEY: stub
          NEXT_PUBLIC_APP_ORIGIN: http://localhost:3000
          SUPABASE_SERVICE_ROLE: stub_service_role
          SEED_ADMIN_EMAIL: ci-admin@example.test
          SEED_ADMIN_PASSWORD: Passw0rd1!
        run: npm run -s build

      - name: Start app (background, tee logs)
        run: |
          npm start 2>&1 | tee .next-app.log & echo $! > .next-app.pid

      - name: Wait for /api/health or homepage (60s)
        run: |
          for i in $(seq 1 60); do
            curl -sf http://localhost:3000/api/health && exit 0
            curl -sf http://localhost:3000/ && exit 0
            sleep 1
          done
          echo "::error::App didn't respond in time"; cat .next-app.log; exit 1

      - name: Stop app
        if: always()
        run: |
          if [ -f .next-app.pid ]; then kill $(cat .next-app.pid) || true; fi

      - name: Upload Next server log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-app-log
          path: .next-app.log
          if-no-files-found: ignore
