name: Release Check (PR smoke)
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions: { contents: read }
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Check lockfile drift (non-blocking)
        id: lock
        shell: bash
        run: |
          if git diff --name-only HEAD~1..HEAD | grep -qE '(^|/)package(-lock)?\.json$'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install deps (lenient for PRs)
        run: npm install --no-audit --no-fund

      - name: Prebuild (route sanity)
        run: node ./scripts/check-dynamic-route-conflicts.mjs

      - name: Prebuild (revalidate sanity)
        run: node ./scripts/assert-valid-revalidate.mjs
      - name: Ensure port 3000 is free
        run: |
          if lsof -i :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
            kill -9 $(lsof -i :3000 -sTCP:LISTEN -t) || true
          fi

      # Optional: you can remove this if you want max speed; kept for parity.
      - name: Build app (non-blocking)
        run: npm run build || echo "skip build for smoke"

      - name: Smoke tests (run against dev server)
        env:
          PLAYWRIGHT_WEBSERVER_CMD: "next dev -p 3000"
          BASE_URL: "http://localhost:3000"
          # safe fallbacks so dev server doesn't crash on missing prod envs
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: "smoke-test-secret"
          NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
          NEXT_PUBLIC_SUPABASE_URL: "http://localhost:54321"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "smoke-test-anon"
        run: npx playwright test "tests/smoke/**/*.spec.ts"
