name: Release Check (PR smoke)
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions: { contents: read }
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Check lockfile drift (non-blocking)
        id: lock
        shell: bash
        run: |
          if git diff --name-only HEAD~1..HEAD | grep -qE '(^|/)package(-lock)?\.json$'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install deps (lenient for PRs)
        run: npm install --no-audit --no-fund

      - name: Prebuild (route sanity)
        run: node ./scripts/check-dynamic-route-conflicts.mjs

      - name: Prebuild (revalidate sanity)
        run: node ./scripts/assert-valid-revalidate.mjs

      - name: Smoke: nav works
        run: npx playwright test tests/smoke/nav.spec.ts
