name: Final QA (full)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr:
        description: PR number
        required: false
      attempt:
        description: Heal attempt
        required: false
      max_heal_rounds:
        description: Max heal rounds override
        required: false

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  qa:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      NODE_ENV: test
      ATTEMPT: ${{ inputs.attempt || 1 }}
      MAX_HEAL_ROUNDS: ${{ inputs.max_heal_rounds || 2 }}
      PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Install Playwright (with deps)
        run: npx playwright install --with-deps

      - name: Resolve Vercel Preview URL
        id: preview
        run: |
          if [ -n "${PREVIEW_URL}" ]; then
            echo "url=${PREVIEW_URL}" >> "$GITHUB_OUTPUT"
          elif [ -n "${VERCEL_PREVIEW_URL}" ]; then
            echo "url=${VERCEL_PREVIEW_URL}" >> "$GITHUB_OUTPUT"
          else
            echo "url=" >> "$GITHUB_OUTPUT"
          fi

      - name: Export BASE_URL
        run: echo "BASE_URL=${{ steps.preview.outputs.url }}" >> $GITHUB_ENV

      - name: Seed test data (non-blocking)
        continue-on-error: true
        shell: bash
        run: |
          echo "Seeding test data at: ${BASE_URL}/api/test/seed"
          curl -v -X POST "${BASE_URL}/api/test/seed" \
            -H "Content-Type: application/json" \
            --data '{}' || echo "⚠️ Seed step failed, continuing..."

      - name: Run smoke tests
        run: npx playwright test --project=smoke
        continue-on-error: true

      - name: Move smoke report
        if: always()
        run: mv playwright-report playwright-report-smoke || true

      - name: Check PH locations health
        id: lochealth
        run: |
          resp=$(curl -fsSL "$BASE_URL/api/locations/health")
          echo "$resp"
          ok=$(echo "$resp" | jq -r '.ok')
          echo "ok=$ok" >> "$GITHUB_OUTPUT"

      - name: Dispatch location self-heal
        if: steps.lochealth.outputs.ok != 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: self_heal
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            {
              "previewUrl": "${{ steps.preview.outputs.url }}",
              "failureCategory": "locations",
              "prNumber": "${{ github.event.pull_request.number }}",
              "headSha": "${{ github.event.pull_request.head.sha }}"
            }

      - name: Fail for bad location health
        if: steps.lochealth.outputs.ok != 'true'
        run: exit 1

      - name: Run QA tests
        id: qa
        run: npx playwright test --project=qa --retries=2 --timeout=60000
        continue-on-error: true

      - name: Move QA report
        if: always()
        run: mv playwright-report playwright-report-qa || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-artifacts
          path: |
            playwright-report-smoke/**
            playwright-report-qa/**
            test-results/**
            tests/qa/coverage.json
          if-no-files-found: ignore
          retention-days: 7

      - name: Trigger self-heal (only if smoke failed)
        if: failure() && steps.lochealth.outputs.ok == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: self_heal
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            {
              "previewUrl": "${{ steps.preview.outputs.url }}",
              "failureCategory": "qa",
              "prNumber": "${{ github.event.pull_request.number }}",
              "headSha": "${{ github.event.pull_request.head.sha }}"
            }

      - name: Self-heal loop controller
        if: failure() && steps.lochealth.outputs.ok == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          max=${MAX_HEAL_ROUNDS:-2}
          attempt=${ATTEMPT:-1}
          pr=${PR_NUMBER}
          if [ "$attempt" -ge "$max" ]; then
            echo "Self-heal rounds exhausted ($attempt/$max)"
            exit 1
          fi
          head_sha="${{ github.event.pull_request.head.sha }}"
          echo "Waiting for Codex commit on PR #${{ github.event.pull_request.number }} (head $head_sha)"
          for i in $(seq 1 30); do
            sleep 60
            new="$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .head.sha)"
            if [ "$new" != "$head_sha" ]; then
              echo "Detected new commit from Codex: $new"
              branch=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .head.ref)
              gh workflow run qa.yml --ref "$branch" -f pr=$pr -f attempt=$((attempt+1))
              exit 0
            fi
          done
          echo "No new Codex commit found."
          exit 1
