name: Final QA (full)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr:
        description: PR number
        required: false
      attempt:
        description: Heal attempt
        required: false
      max_heal_rounds:
        description: Max heal rounds override
        required: false

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  qa:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      NODE_ENV: test
      ATTEMPT: ${{ inputs.attempt || 1 }}
      MAX_HEAL_ROUNDS: ${{ inputs.max_heal_rounds || 2 }}
      PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Install Playwright (with deps)
        run: npx playwright install --with-deps

      - name: Resolve Vercel Preview URL
        id: preview
        run: |
          if [ -n "${PREVIEW_URL}" ]; then
            echo "url=${PREVIEW_URL}" >> "$GITHUB_OUTPUT"
          elif [ -n "${VERCEL_PREVIEW_URL}" ]; then
            echo "url=${VERCEL_PREVIEW_URL}" >> "$GITHUB_OUTPUT"
          else
            echo "url=" >> "$GITHUB_OUTPUT"
          fi

      - name: Export BASE_URL
        run: echo "BASE_URL=${{ steps.preview.outputs.url }}" >> $GITHUB_ENV

      - name: Seed test data (non-blocking)
        continue-on-error: true
        shell: bash
        run: |
          echo "Seeding test data at: ${BASE_URL}/api/test/seed"
          curl -v -X POST "${BASE_URL}/api/test/seed" \
            -H "Content-Type: application/json" \
            --data '{}' || echo "⚠️ Seed step failed, continuing..."

      - name: Run smoke tests
        run: npx playwright test --project=smoke
        continue-on-error: true

      - name: Move smoke report
        if: always()
        run: mv playwright-report playwright-report-smoke || true

      - name: Run QA tests
        id: qa
        run: npx playwright test --project=qa --retries=2 --timeout=60000
        continue-on-error: true

      - name: Move QA report
        if: always()
        run: mv playwright-report playwright-report-qa || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-artifacts
          path: |
            playwright-report-smoke/**
            playwright-report-qa/**
            test-results/**
            tests/qa/coverage.json
          if-no-files-found: ignore
          retention-days: 7

      - name: Trigger self-heal (only if smoke failed)
        if: failure()
        uses: benc-uk/workflow-dispatch@v1
        continue-on-error: true
        with:
          workflow: self_heal
          ref: ${{ github.head_ref || github.ref_name }}
        
          inputs: '{"pr_number":"${{ github.event.pull_request.number || '' }}"}'

      - name: Self-heal loop controller
        if: failure()
        run: |
          echo "Waiting for potential self-heal commit…"
          # keep this as a no-op watcher to avoid hard failures
          sleep 10
        continue-on-error: true
