name: Release check

on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install deps
        run: npm run ci:install

      - name: Verify lockfile
        run: npm run ci:check-lock

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Get Vercel preview URL
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: node scripts/get-vercel-preview-url.mjs > url.txt

      - name: Export BASE_URL
        run: echo "BASE_URL=$(cat url.txt)" >> $GITHUB_ENV

      - name: Seed test data
        env:
          QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
          QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run ci:seed

      - name: Run smoke tests
        run: npm run test:smoke:ci

      - name: Run full e2e tests
        run: npm run test:e2e:ci

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore

      - name: Create summary
        if: always()
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: node scripts/ci-summary.mjs > summary.md

      - name: Post PR comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });

