name: Release Check (PR smoke)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DISABLE_STRIPE: '1'
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL || 'https://example.supabase.co' }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'test-anon-key' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .next/**/*.html
            **/playwright-report/**

  e2e_smoke:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      DISABLE_STRIPE: '1'
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL || 'https://example.supabase.co' }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'test-anon-key' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npx playwright install --with-deps
      - name: Smoke (landing↔app CTAs)
        env:
          PREVIEW_URL: ${{ vars.PREVIEW_URL || env.PREVIEW_URL }}
          LANDING_URL: ${{ vars.LANDING_URL || env.LANDING_URL }}
        run: |
          npx playwright test e2e/landing-post.spec.ts --reporter=line
          npx playwright test e2e/app-home-search.spec.ts --reporter=line
      - run: npm run test:smoke
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-smoke
          path: |
            playwright-report/**
            test-results/**
          if-no-files-found: ignore
