name: Release Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (robust)
        run: npm ci --no-audit --no-fund

      - name: Install Playwright (with system deps)
        run: npx playwright install --with-deps

      # Get Vercel preview URL (ORG optional)
      - name: Get Vercel preview URL
        id: preview
        run: |
          node scripts/get-vercel-preview-url.mjs > url.txt
          echo "BASE_URL=$(cat url.txt)" >> $GITHUB_ENV
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Echo preview
        run: echo "Testing $BASE_URL"

      # Seed preview (best-effort)
      - name: Seed test data (Preview)
        run: node scripts/seed-preview.mjs
        env:
          BASE_URL: ${{ env.BASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SEED_ADMIN_EMAIL: ${{ secrets.SEED_ADMIN_EMAIL }}

      # Smoke tests
      - name: Run smoke tests
        run: npx playwright test tests/smoke --reporter=github
        env:
          BASE_URL: ${{ env.BASE_URL }}

      # Full E2E
      - name: Run full E2E
        run: npx playwright test tests/e2e --reporter=github
        env:
          BASE_URL: ${{ env.BASE_URL }}

      # Always upload artifacts
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore

