name: Release Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DISABLE_STRIPE: '1'
  NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
  NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon
  PLAYWRIGHT_BASE_URL: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Harden npm & retry more (429-safe)
        run: |
          npm config set audit false fund false
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-maxtimeout 120000

      - name: Install deps
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: next-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('**/*.ts','**/*.tsx','package-lock.json','next.config.js','tsconfig.json') }}
          restore-keys: |
            next-${{ runner.os }}-${{ github.ref_name }}-

      - name: Build
        run: npm run build

      - name: Pack build for shards
        run: |
          tar -czf build.tgz .next public package.json next.config.js

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: build.tgz
          if-no-files-found: error

  e2e_full:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - shard: 1/2
            shard_label: 1-of-2
          - shard: 2/2
            shard_label: 2-of-2
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Harden npm & retry more (429-safe)
        run: |
          npm config set audit false fund false
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-maxtimeout 120000

      - name: Install deps
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .

      - name: Unpack build
        run: tar -xzf build.tgz

      - name: Install Playwright (system deps)
        run: npx playwright install --with-deps

      - name: Run E2E tests (shard ${{ matrix.shard_label }})
        env:
          WORKER_EMAIL: ${{ secrets.WORKER_EMAIL }}
          WORKER_PASSWORD: ${{ secrets.WORKER_PASSWORD }}
          EMPLOYER_EMAIL: ${{ secrets.EMPLOYER_EMAIL }}
          EMPLOYER_PASSWORD: ${{ secrets.EMPLOYER_PASSWORD }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          CI_FAST: '1'
        run: npx playwright test --shard ${{ matrix.shard }} --reporter=github,html

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shard_label }}
          path: playwright-report/**
