name: Codex self-heal

on:
  workflow_dispatch:
    inputs:
      previewUrl:
        description: "Deployed preview URL"
        required: true
        type: string
      failureCategory:
        description: "Failure category to heal"
        required: true
        type: string
      prNumber:
        description: "Pull Request number"
        required: true
        type: string
      headSha:
        description: "Commit SHA to rerun QA on"
        required: true
        type: string

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  self-heal:
    runs-on: ubuntu-latest
    env:
      PREVIEW_URL: ${{ inputs.previewUrl }}
      FAILURE_CATEGORY: ${{ inputs.failureCategory }}
      PR_NUMBER: ${{ inputs.prNumber }}
      HEAD_SHA: ${{ inputs.headSha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Repair PH locations
        if: env.FAILURE_CATEGORY == 'locations'
        run: |
          curl -fsSL -X POST "$PREVIEW_URL/api/locations/repair" \
            -H "x-self-heal: ${{ secrets.SELF_HEAL_TOKEN }}"

      - name: Verify PH locations
        if: env.FAILURE_CATEGORY == 'locations'
        run: |
          resp=$(curl -fsSL "$PREVIEW_URL/api/locations/health")
          echo "$resp"
          ok=$(echo "$resp" | jq -r '.ok')
          if [ "$ok" != "true" ]; then
            echo "Location repair failed"
            exit 1
          fi

      - name: Re-run QA
        if: env.FAILURE_CATEGORY == 'locations'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run qa.yml --ref "$HEAD_SHA" -f pr="$PR_NUMBER" -f attempt=2
