name: Self Heal
on:
  workflow_run:
    workflows: ["Release Check (PR smoke)", "Final QA (full)"]
    types: [completed]
permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  heal:
    if: ${{ contains(fromJson('["failure","cancelled","timed_out"]'), github.event.workflow_run.conclusion) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Post note if artifacts exist
        uses: actions/github-script@v7
        with:
          script: |
            core.info('Self-heal bootstrap active. A follow-up PR can push automated fixes.')
