name: Self Heal
on:
  workflow_run:
    types: [completed]   # listen to all workflows
permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  heal:
    # ignore running on itself; trigger on failed/cancelled/timeout PR runs only
    if: >
      ${{
        github.event.workflow_run.name != 'Self Heal' &&
        github.event.workflow_run.event == 'pull_request' &&
        contains(fromJson('["failure","cancelled","timed_out"]'), github.event.workflow_run.conclusion)
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run healer
        run: node scripts/self-heal/run.js
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
