name: Self Heal
on:
  workflow_run:
    workflows: ["Release Check (PR smoke)"]
    types: [completed]
jobs:
  heal:
    if: ${{ contains(fromJson('["failure","cancelled","timed_out"]'), github.event.workflow_run.conclusion) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run healer
        run: node scripts/self-heal/run.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
