name: Smoke

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      QA_TEST_MODE: "true"
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
      TEST_LOGIN_SECRET: ${{ secrets.TEST_LOGIN_SECRET }}
      TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_TEST_LOGIN_ENABLED: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci --no-audit --no-fund
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Get Vercel Preview URL
        run: node scripts/get-vercel-preview-url.mjs
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GITHUB_SHA: ${{ github.sha }}
      - run: |
          URL=$(cat url.txt)
          echo "BASE_URL=$URL" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_APP_URL=$URL" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SITE_URL=$URL" >> $GITHUB_ENV
      - name: Seed test data (best effort)
        run: |
          curl -fsS "$BASE_URL/api/test/seed?secret=${{ secrets.QA_TEST_SECRET }}&mode=preview" \
            || echo "::warning::Seed failed"
      - name: Run smoke tests
        run: npx playwright test tests/smoke --config=playwright.ci.ts --reporter=github
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            playwright-report
            test-results
          if-no-files-found: ignore
