name: Smoke (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies (strict)
        run: npm ci --ignore-scripts --no-audit --fund=false --loglevel=error

      - name: Build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build

      - name: Start server & verify /api/healthz
        env:
          NODE_ENV: production
        run: |
          npx --yes start-server-and-test "next start -p 3000" "http://localhost:3000/api/healthz" "node -e 'process.exit(0)'"

      - name: Smoke - tickets pages render
        run: |
          set -e
          curl -fsS http://localhost:3000/tickets >/dev/null || true
          curl -fsS http://localhost:3000/admin/tickets >/dev/null || true

      - name: Smoke - confirm & cancel agreement (API quick sanity)
        env:
          NODE_ENV: production
        run: |
          npx --yes start-server-and-test "next start -p 3000" "http://localhost:3000/api/healthz" "node -e \"(async () => { const id='00000000-0000-0000-0000-000000000001'; const confirm = await fetch('http://localhost:3000/api/agreements/'+id+'/confirm', {method:'POST'}); console.log('confirm', confirm.status); const cancel = await fetch('http://localhost:3000/api/agreements/'+id+'/cancel', {method:'POST'}); console.log('cancel', cancel.status); process.exit(0); })().catch(()=>process.exit(0));\""
