name: Smoke (PR)

on:
  pull_request:
    branches: [ main ]

jobs:
  pr:
    name: Run smoke
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci --no-audit --fund=false --loglevel=error
      - run: npx playwright install --with-deps chromium
      - name: Build
        run: npm run build
      - name: Start server and run smoke
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          PORT: "3000"
          NEXT_PUBLIC_SUPABASE_URL: "http://localhost:54321"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "test_anon_key"
          SUPABASE_URL: "http://localhost:54321"
          SUPABASE_ANON_KEY: "test_anon_key"
          SUPABASE_SERVICE_ROLE_KEY: "test_service_role"
          SMOKE: "1"
        run: npx start-server-and-test \
             "npm run start" http-get://localhost:3000/api/healthz \
             "npx playwright test -c playwright.smoke.ts"
