name: Smoke

on:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Check env
        run: node -e "['VERCEL_TOKEN','VERCEL_PROJECT_ID','QA_TEST_SECRET','NEXT_PUBLIC_SUPABASE_URL','NEXT_PUBLIC_SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY','SEED_ADMIN_EMAIL'].forEach(k=>{if(!process.env[k]){console.error('Missing '+k);process.exit(1);}})"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SEED_ADMIN_EMAIL: ${{ secrets.SEED_ADMIN_EMAIL }}
      - name: Install deps
        run: npm run ci:install
      - name: Verify lockfile unchanged
        run: npm run ci:check-lock
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Get Vercel Preview URL
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: node scripts/get-vercel-preview-url.mjs > url.txt
      - run: echo "BASE_URL=$(cat url.txt)" >> $GITHUB_ENV
      - name: Seed
        run: |
          curl -fsSL -X POST "$BASE_URL/api/test/seed" -H "x-test-secret: ${{ secrets.QA_TEST_SECRET }}" || true
      - name: Run smoke
        run: npx playwright test -c playwright.ci.ts tests/smoke
        env:
          CI: 'true'
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-results
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore
