name: Smoke (PR)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lock_guard:
    name: Lock Guard
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/lock-guard

  smoke:
    name: Run smoke (pull_request)
    runs-on: ubuntu-22.04
    needs: lock_guard
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install deps
        run: npm ci --ignore-scripts --no-audit --fund=false --loglevel=error
      - name: Install Playwright browsers (first run caches)
        run: npx playwright install --with-deps chromium
      - name: Build Next.js
        run: npm run build
      - name: Start server and run smoke
        env:
          NODE_ENV: production
        run: |
          npx wait-on --version || npm i -D wait-on
          npm run start-server-and-test
