name: Smoke

on:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      QA_TEST_EMAIL: ${{ secrets.QA_TEST_EMAIL }}
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
      SEED_ADMIN_EMAIL: ${{ secrets.SEED_ADMIN_EMAIL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install deps
        run: npm run ci:install
      - name: Verify lockfile
        run: npm run ci:check-lock
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Get Vercel preview URL
        run: echo "BASE_URL=$(node scripts/get-vercel-preview-url.mjs)" >> $GITHUB_ENV
      - name: Seed test data
        run: npm run ci:seed:preview
      - name: Run smoke tests
        run: npm run test:smoke:ci -- --output=test-results/smoke
        env:
          PLAYWRIGHT_HTML_REPORT: playwright-report/smoke
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            playwright-report/**
            test-results/**
            **/trace.zip
          if-no-files-found: ignore
