name: Smoke (main)

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'src/**'
      - 'pages/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'playwright*.{js,ts}'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: smoke-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            pw-${{ runner.os }}-

      - run: npm ci

      - name: Install Playwright (Chromium)
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        run: npx playwright install --with-deps chromium

      - name: Start dev server
        run: |
          npm run dev & echo $! > .pidfile
      - name: Wait for server
        run: npx --yes wait-on http://localhost:3000

      - name: Smoke tests (no webServer)
        run: npx playwright test -c playwright.smoke.ts

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/**

      - name: Stop dev server
        if: always()
        run: |
          if [ -f .pidfile ]; then kill $(cat .pidfile) || true; fi
