name: Smoke (push)

on:
  push:
    branches: [main]

concurrency:
  group: smoke-push
  cancel-in-progress: true

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      AUTH_PKCE_ENABLED: 'false'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: node -v && npm -v
      - run: npm run preflight:node
      - name: Verify lock sync
        run: npm run ci:lock
      - name: Install deps
        run: npm run ci:install
      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
      - name: Start dev server
        run: |
          nohup npm run dev >/dev/null 2>&1 &
          echo $! > .pidfile
      - name: Wait for dev server
        run: |
          for i in {1..60}; do
            curl -fsS http://localhost:3000 >/dev/null && exit 0
            sleep 1
          done
          echo "Dev server failed to start" && exit 1
      - name: Run smoke tests (no webServer)
        run: npx playwright test -c playwright.smoke.ts
        env:
          BASE_URL: http://localhost:3000
      - name: Stop dev server
        if: always()
        run: if [ -f .pidfile ]; then kill $(cat .pidfile) || true; fi
