name: Run Smoke (manual)
on:
  workflow_dispatch:
    inputs:
      baseUrl:
        description: 'App base URL'
        required: false
        default: 'http://localhost:3000'
permissions:
  contents: read
concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true
jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable pnpm (corepack)
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build
        run: pnpm build

      - name: Start app (background)
        run: |
          (nohup pnpm start > .next/serve.log 2>&1 &)
          echo "Started Next on :3000"

      - name: Wait for app
        run: |
          for i in {1..60}; do
            if curl -fsSL "${{ github.event.inputs.baseUrl }}" >/dev/null 2>&1; then echo "App is up"; exit 0; fi
            sleep 2
          done
          echo "App did not become healthy in time"; cat .next/serve.log || true; exit 1

      - name: Run smoke
        env:
          RUN_SMOKE: "true"
          BASE_URL: ${{ github.event.inputs.baseUrl }}
        run: |
          pnpm exec playwright test tests/smoke.* --reporter=line || pnpm exec playwright show-report
