name: Smoke

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      QA_TEST_MODE: "true"
      QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
      TEST_LOGIN_SECRET: ${{ secrets.TEST_LOGIN_SECRET }}
      TEST_LOGIN_ENABLED: "true"
      NEXT_PUBLIC_TEST_LOGIN_ENABLED: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (robust)
        run: npm install --legacy-peer-deps --no-audit
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Get Vercel Preview URL for this commit
        run: node scripts/get-vercel-preview-url.mjs > url.txt
      - name: Export BASE_URL
        run: echo "BASE_URL=$(cat url.txt)" >> $GITHUB_ENV
      - name: Seed test data (Preview)
        env:
          BASE_URL: ${{ env.BASE_URL }}
          QA_TEST_SECRET: ${{ secrets.QA_TEST_SECRET }}
        run: node scripts/seed-ci.mjs
      - name: Run smoke tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
        run: npx playwright test tests/smoke --config=playwright.ci.ts
