name: Smoke (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies (strict)
        run: npm ci --ignore-scripts --no-audit --fund=false --loglevel=error

      - name: Build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build
      - name: Check CTA links
        run: |
          npx --yes start-server-and-test "next start -p 3000" "http://localhost:3000" "node scripts/check-cta-links.mjs"

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

      - name: Run smoke tests
        env:
          NODE_ENV: production
        run: |
          npx --yes start-server-and-test "next start -p 3000" "http://localhost:3000" "npx playwright test -c playwright.smoke.ts"
