name: Smoke

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Branch / Event
        run: |
          echo "event: ${{ github.event_name }}"
          echo "ref: ${{ github.ref }}"

      # 👉 PRs: DO NOT block on external checks (runners may block CONNECT).
      - name: PR soft check (headers only, non-blocking)
        if: ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          set -x
          curl -I -L --max-time 8 --retry 1 https://app.quickgig.ph || true
          curl -I -L --max-time 8 --retry 1 https://quickgig.ph || true
          curl -I -L --max-time 8 --retry 1 https://www.quickgig.ph || true
          echo "::notice::PR soft check completed (non-blocking)."

      # 👉 main: still check, but warn-only (never fail deploys)
      - name: Main branch external check (warn-only)
        if: ${{ github.ref == 'refs/heads/main' }}
        continue-on-error: true
        run: |
          set -x
          echo "Checking production endpoints..."
          curl -I -L --max-time 10 --retry 2 https://app.quickgig.ph || true
          curl -I -L --max-time 10 --retry 2 https://quickgig.ph || true
          curl -I -L --max-time 10 --retry 2 https://www.quickgig.ph || true
          echo "::notice::Main branch external check done (warn-only)."

      # Keep any existing build/lint/type steps if they lived in this file before.
