name: Smoke (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    continue-on-error: true
    env:
      NEXT_PUBLIC_APP_HOST: http://localhost:3000
      AUTH_PKCE_OPTIONAL: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: node -v && npm -v

      - run: npm run preflight:node

      - name: Install dependencies (strict)
        run: npm ci --ignore-scripts --no-audit --fund=false --loglevel=error

      - name: Build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'
          # compile with CI mock rewrites enabled
          MOCK_MODE: '1'
          NEXT_PUBLIC_SUPABASE_URL: 'https://example.invalid'
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'dummy'
        run: npm run build
      - name: Check CTA links
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: '1'
          MOCK_MODE: '1'
          NEXT_PUBLIC_SUPABASE_URL: 'https://example.invalid'
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'dummy'
        run: |
          npx --yes start-server-and-test \
            "next start -p 3000" \
            "http://localhost:3000/api/healthz" \
            "node scripts/audit-links.mjs"
        # If this step ever proves flaky, uncomment the next line temporarily:
        # continue-on-error: true
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Setup Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          install-deps: true

      - name: Verify browsers installed (and force install if needed)
        run: |
          npx playwright --version || true
          npx playwright install --with-deps chromium
          ls -la ~/.cache/ms-playwright || true
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ""

      - name: Run smoke tests
        env:
          NODE_ENV: production
          MOCK_MODE: "1"
          NEXT_PUBLIC_SUPABASE_URL: "https://example.invalid"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "dummy"
          AUTH_PKCE_OPTIONAL: "true"
          NEXT_PUBLIC_APP_HOST: "http://localhost:3000"
        run: |
          npx --yes start-server-and-test "next start -p 3000" "http://localhost:3000" "npx playwright test -c playwright.smoke.ts"
