name: Status Report
on:
  workflow_dispatch:
  schedule:
    - cron: "32 6 * * *" # daily snapshot
  pull_request:
    paths:
      - "scripts/status/**"
      - ".github/workflows/status-report.yml"
      - "docs/status/**"
  push:
    branches: [ main ]
    paths:
      - "scripts/status/**"
      - ".github/workflows/status-report.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Generate status snapshot (no build, no deps)
        run: node scripts/status/report.mjs

      - name: Create PR with snapshot (if changed)
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(status): update status snapshot"
          title: "chore(status): update status snapshot"
          body: |
            Automated status snapshot that reflects the current contract.

            - Canonical routes: /browse-jobs, /post-job, /applications, /login
            - Auth-aware redirects via /login?next=<dest> allowed in smokes
            - Legacy /gigs/create is not canonical
          branch: chore/status-snapshot-${{ github.run_id }}
          labels: documentation, status
          add-paths: |
            docs/status/status-*.md

      - name: Post Status Report
        if: always()
        shell: bash
        run: |
          {
            echo "# QuickGig Status Report"
            echo
            echo "## Contract (enforced by docs/workflow)"
            echo "- Canonical app routes: /browse-jobs, /post-job, /applications, /login"
            echo "- Auth-aware redirects (\`/login?next=<dest>\`) are treated as success in smokes"
            echo "- Legacy \`/gigs/create\` is not canonical"
          } >> "$GITHUB_STEP_SUMMARY"

