name: Status report

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Days to look back (default 30)'
        required: false
        default: '30'
  schedule:
    - cron: '0 0 * * 0' # weekly, UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-22.04
    env:
      # make token available to Node/Octokit/gh and scripts
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install deps (quiet, resilient)
        run: npm ci --ignore-scripts --no-audit --fund=false --loglevel=error

      - name: Generate status report
        env:
          REPORT_LOOKBACK_DAYS: ${{ github.event.inputs.days || '30' }}
        run: npm run report:status

      - name: Compute date slug (UTC)
        id: meta
        run: echo "today=$(date -u +%F)" >> "$GITHUB_OUTPUT"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: status-${{ steps.meta.outputs.today }}
          path: |
            status/status-${{ steps.meta.outputs.today }}.md
            status/index.json
          if-no-files-found: warn

      - name: Create PR with report
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: status/${{ steps.meta.outputs.today }}
          base: main
          title: "Status report: ${{ steps.meta.outputs.today }}"
          commit-message: "chore(status): add ${{ steps.meta.outputs.today }} report"
          body: |
            Automated status report for ${{ steps.meta.outputs.today }}.
            Generated by CI and uploaded as an artifact.
