name: Status Report

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (CI)
        run: npm ci --ignore-scripts --no-audit --fund=false --loglevel=error

      - name: Run guardrails (non-blocking)
        shell: bash
        run: |
          set +e
          if [ -f scripts/no-legacy.sh ]; then
            bash scripts/no-legacy.sh > no-legacy.txt 2>&1 || true
          else
            echo "scripts/no-legacy.sh not found (skipped)" > no-legacy.txt
          fi

          if [ -f scripts/check-cta-links.mjs ]; then
            node scripts/check-cta-links.mjs > cta-audit.txt 2>&1 || true
          else
            echo "scripts/check-cta-links.mjs not found (skipped)" > cta-audit.txt
          fi

      - name: Post Status Report
        shell: bash
        run: |
          echo "# QuickGig Status Report" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "## Contract (enforced by tests & scripts)" >> "$GITHUB_STEP_SUMMARY"
          echo "- Canonical app routes: /browse-jobs, /gigs/create, /applications, /login" >> "$GITHUB_STEP_SUMMARY"
          echo "- Auth-aware redirects (/login?next=<dest>) are treated as success in smoke" >> "$GITHUB_STEP_SUMMARY"
          echo "- Header & hero CTAs use central ROUTES + toAppPath(), with stable test IDs (desktop & mobile)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "## Guardrail: scripts/no-legacy.sh" >> "$GITHUB_STEP_SUMMARY"
          sed -n '1,200p' no-legacy.txt >> "$GITHUB_STEP_SUMMARY" || true
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "## Guardrail: scripts/check-cta-links.mjs" >> "$GITHUB_STEP_SUMMARY"
          sed -n '1,200p' cta-audit.txt >> "$GITHUB_STEP_SUMMARY" || true
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "## Local verification commands" >> "$GITHUB_STEP_SUMMARY"
          echo "\`bash scripts/no-legacy.sh\` and \`node scripts/check-cta-links.mjs\`" >> "$GITHUB_STEP_SUMMARY"
          echo "\`npx playwright test -c playwright.smoke.ts\`" >> "$GITHUB_STEP_SUMMARY"
