name: Status Report

on:
  pull_request:
    paths:
      - '.github/workflows/status-report.yml'
      - 'docs/status/**'
      - 'scripts/status/**'

  workflow_dispatch:
    inputs:
      backfill_days:
        description: 'Backfill N previous days (0 = none)'
        required: false
        default: '0'

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Generate status snapshot (no build, no deps)
        shell: bash
        run: |
          if [ -f scripts/status/snapshot.mjs ]; then
            node scripts/status/snapshot.mjs
          elif [ -f scripts/status/snapshot.cjs ]; then
            node scripts/status/snapshot.cjs
          elif [ -f scripts/status/snapshot.sh ]; then
            bash scripts/status/snapshot.sh
          else
            node -e '
              const fs=require("fs");
              fs.mkdirSync("docs/status",{recursive:true});
              const d=new Date(), z=n=>String(n).padStart(2,"0");
              const date=`${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`;
              const out=`docs/status/status-${date}.md`;
              const md=`# QuickGig Status — ${date}

## What must stay true (current contract)
- Canonical app routes: **/browse-jobs**, **/post-job**, **/applications**, **/login**
- Legacy routes must redirect to canonical: **/post-jobs**, **/gigs/create** → **/post-job**
- Signed-out flows that land on **/login?next=<dest>** are considered **success** in smoke
`;
              const cur=fs.existsSync(out)?fs.readFileSync(out,"utf8"):"";
              if(cur.trim()!==md.trim()) fs.writeFileSync(out,md);
            '
          fi

      - name: Backfill past snapshots (optional)
        if: ${{ inputs.backfill_days != '0' }}
        shell: bash
        run: |
          if [ -f scripts/status/backfill.mjs ]; then
            node scripts/status/backfill.mjs "${{ inputs.backfill_days }}"
          else
            echo "No backfill script present; skipping."
          fi

      # NEW: detect changes AFTER backfill, including untracked files
      - name: Detect docs/status changes (incl. untracked)
        id: detect
        shell: bash
        run: |
          # stage intent so git diff sees path changes without committing
          git add -N docs/status >/dev/null 2>&1 || true

          CHANGED_TRACKED=0
          git diff --quiet -- docs/status || CHANGED_TRACKED=1

          UNTRACKED="$(git ls-files --others --exclude-standard docs/status || true)"

          if [ "$CHANGED_TRACKED" -eq 1 ] || [ -n "$UNTRACKED" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR with snapshot (if changed)
        if: steps.detect.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(status): add/update status snapshot"
          title: "chore(status): add/update status snapshot"
          body: |
            Automated snapshot update.

            Contract (enforced):
            - Canonical app routes: /browse-jobs, /post-job, /applications, /login
            - Legacy routes redirect to canonical: /post-jobs, /gigs/create → /post-job
            - Auth-aware redirects (/login?next=<dest>) are treated as success in smoke
          branch: snapshot
          base: ${{ github.base_ref || 'main' }}
          add-paths: |
            docs/status/**

      - name: Post Status Report
        shell: bash
        run: |
          {
            echo "# QuickGig Status Report"
            echo
            echo "## Contract (enforced by tests & scripts)"
            echo "- Canonical app routes: /browse-jobs, /post-job, /applications, /login"
            echo "- Legacy routes redirect to canonical: /post-jobs, /gigs/create -> /post-job"
            echo "- Auth-aware redirects (/login?next=<dest>) count as success in smoke"
            echo
            echo "## Snapshot"
            echo "- Changes detected: ${{ steps.detect.outputs.changed }}"
          } >> "$GITHUB_STEP_SUMMARY"

