name: Status Report

on:
  workflow_dispatch:
    inputs:
      backfill_days:
        description: "Backfill N previous days (e.g. 7). 0 = no backfill."
        required: false
        default: "0"
  pull_request:
    paths:
      - ".github/workflows/status-report.yml"
      - "docs/status/**"
      - "scripts/status/status-snapshot.sh"
  schedule:
    # Weekdays at 09:00 UTC; harmless if it runs, will no-op when unchanged
    - cron: "0 9 * * 1-5"

permissions:
  contents: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Prepare env
        id: prep
        run: |
          echo "SNAPSHOT_DATE=$(date -u +%F)" >> "$GITHUB_OUTPUT"

      - name: Generate status snapshot (no build, no deps)
        id: snapshot
        run: |
          echo "Generating status snapshot…"
          chmod +x ./scripts/status/status-snapshot.sh
          ./scripts/status/status-snapshot.sh "${{ steps.prep.outputs.SNAPSHOT_DATE }}"
          # Tell downstream steps if the docs changed
          if ! git diff --quiet -- docs/status; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Backfill past snapshots (optional)
        if: ${{ inputs.backfill_days != '0' }}
        run: node scripts/status/backfill.mjs ${{ inputs.backfill_days }}

      - name: Post Status Report
        shell: bash
        run: |
          echo "# QuickGig Status Report" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "## Snapshot (${{ steps.prep.outputs.SNAPSHOT_DATE }})" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          cat "docs/status/latest.md" >> "$GITHUB_STEP_SUMMARY"

      - name: Create PR with snapshot (if changed)
        if: steps.snapshot.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(status): status snapshot ${{ steps.prep.outputs.SNAPSHOT_DATE }}"
          commit-message: "chore(status): snapshot ${{ steps.prep.outputs.SNAPSHOT_DATE }}"
          body: "Automated status snapshot. Skips PR if no changes."
          branch: "chore/status-snapshot/${{ steps.prep.outputs.SNAPSHOT_DATE }}"
          base: main
          add-paths: |
            docs/status/status-${{ steps.prep.outputs.SNAPSHOT_DATE }}.md
            docs/status/latest.md

