name: Supabase schema pull
on:
  workflow_dispatch: {}
  # Optional: uncomment to allow nightly refresh
  # schedule:
  #   - cron: "0 6 * * *"

jobs:
  pull:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable pnpm (corepack)
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm --version
      - name: Install Supabase CLI
        run: pnpm add -g supabase@2

      - name: Show Supabase CLI version
        run: supabase --version

      - name: Build DB_URL from secrets
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          set -eu
          if [ -z "${SUPABASE_PROJECT_REF:-}" ] || [ -z "${SUPABASE_DB_PASSWORD:-}" ]; then
            echo "::error::Missing SUPABASE_PROJECT_REF or SUPABASE_DB_PASSWORD secrets"
            exit 1
          fi
          echo "DB_URL=postgresql://postgres:${SUPABASE_DB_PASSWORD}@db.${SUPABASE_PROJECT_REF}.supabase.co:5432/postgres" >> $GITHUB_ENV

      - name: Pull live schema
        env:
          DB_URL: ${{ env.DB_URL }}
        run: |
          set -eu
          supabase db pull --db-url "$DB_URL"

      - name: Create PR with pulled schema
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(db): pull live schema baseline"
          title: "chore(db): pull live schema baseline"
          body: |
            This PR was opened automatically by the Supabase schema pull workflow.
            It snapshots the **live** database schema into the repo so migrations and code stay in sync.
          branch: ci/supabase-db-pull
          delete-branch: true
