name: Supabase migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Supabase version
        run: supabase --version
      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          set -eu
          supabase link \
            --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}" \
            --password    "${{ secrets.SUPABASE_DB_PASSWORD }}"
      - name: Apply migrations (main)
        run: |
          set -eu
          supabase db push --non-interactive
